#!/usr/bin/env python3
"""
context_snapshot.py — Generate a vault-state.md context snapshot from SQLite.

Reads the projects and roadmap_items tables and writes a structured markdown
summary. This file is what an AI agent loads at session start to understand
the current state of the vault without scanning all markdown files.

The pre-computed context pattern: run this after each sync, load the output
at agent start time. Fast (no embedding call), always current, and small
enough to fit in a context window.

Usage:
    python brain/context_snapshot.py                # writes vault-state.md
    python brain/context_snapshot.py --stdout       # print to terminal instead
    python brain/context_snapshot.py --db path/to/brain.db

Env vars (via .env or shell):
    VAULT_PATH   Path to the vault directory (default: ~/vault)
    DB_PATH      Path to brain.db (default: ~/vault/_data/brain.db)
"""

import argparse
import os
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

VAULT_PATH = Path(os.environ.get("VAULT_PATH", "~/vault")).expanduser()
DB_PATH    = Path(os.environ.get("DB_PATH", "~/vault/_data/brain.db")).expanduser()


# ---------------------------------------------------------------------------
# Database
# ---------------------------------------------------------------------------

def get_read_conn(db_path: Path) -> sqlite3.Connection:
    """Open a read-only SQLite connection."""
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    return conn


# ---------------------------------------------------------------------------
# Queries
# ---------------------------------------------------------------------------

def query_projects(conn: sqlite3.Connection) -> dict[str, list[dict]]:
    """Fetch all projects bucketed by status."""
    rows = conn.execute(
        "SELECT slug, title, status, started, summary, repo, tags FROM projects ORDER BY slug"
    ).fetchall()

    buckets: dict[str, list[dict]] = {
        "active": [],
        "planned": [],
        "complete": [],
        "other": [],
    }

    for row in rows:
        status = (row["status"] or "planned").lower()
        bucket = status if status in buckets else "other"
        buckets[bucket].append(dict(row))

    return buckets


def query_roadmap(conn: sqlite3.Connection) -> dict[str, list[dict]]:
    """Fetch all roadmap items bucketed by status."""
    rows = conn.execute(
        """
        SELECT r.slug, r.title, r.status, r.project, r.priority, r.due
        FROM roadmap_items r
        ORDER BY
            CASE r.priority WHEN 'high' THEN 0 WHEN 'medium' THEN 1 ELSE 2 END,
            r.slug
        """
    ).fetchall()

    buckets: dict[str, list[dict]] = {
        "in-progress": [],
        "planned": [],
        "blocked": [],
        "done": [],
        "other": [],
    }

    for row in rows:
        status = (row["status"] or "planned").lower()
        bucket = status if status in buckets else "other"
        buckets[bucket].append(dict(row))

    return buckets


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------

def render(projects: dict, roadmap: dict) -> str:
    """Render the vault-state.md content from query results."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    total_projects = sum(len(v) for v in projects.values())
    total_roadmap  = sum(len(v) for v in roadmap.values())

    lines = [
        "<!-- Do not edit — auto-generated by context_snapshot.py -->",
        "",
        "# Vault State",
        "",
        f"*Generated: {now}*",
        "",
        f"**{total_projects} projects** | **{total_roadmap} roadmap items**",
        "",
    ]

    # --- Projects ---
    lines.append("## Projects")
    lines.append("")

    if projects["active"]:
        lines.append("### Active")
        lines.append("")
        for p in projects["active"]:
            summary = f" — {p['summary']}" if p.get("summary") else ""
            repo = f" ([repo]({p['repo']}))" if p.get("repo") else ""
            lines.append(f"- **{p['title']}** (`{p['slug']}`){summary}{repo}")
        lines.append("")

    if projects["planned"]:
        lines.append("### Planned")
        lines.append("")
        for p in projects["planned"]:
            summary = f" — {p['summary']}" if p.get("summary") else ""
            lines.append(f"- **{p['title']}** (`{p['slug']}`){summary}")
        lines.append("")

    if projects["complete"]:
        lines.append("### Complete")
        lines.append("")
        for p in projects["complete"]:
            lines.append(f"- {p['title']} (`{p['slug']}`)")
        lines.append("")

    if projects["other"]:
        lines.append("### Other")
        lines.append("")
        for p in projects["other"]:
            lines.append(f"- {p['title']} (`{p['slug']}`) — status: {p['status']}")
        lines.append("")

    # --- Roadmap ---
    lines.append("## Roadmap")
    lines.append("")

    priority_label = {"high": "🔴", "medium": "🟡", "low": "⚪"}

    for status_key, heading in [
        ("in-progress", "In Progress"),
        ("planned", "Planned"),
        ("blocked", "Blocked"),
    ]:
        items = roadmap[status_key]
        if not items:
            continue
        lines.append(f"### {heading}")
        lines.append("")
        for item in items:
            pri = priority_label.get(item.get("priority", "medium"), "")
            project = f" [{item['project']}]" if item.get("project") else ""
            due = f" due {item['due']}" if item.get("due") else ""
            lines.append(f"- {pri} **{item['title']}** (`{item['slug']}`){project}{due}")
        lines.append("")

    if roadmap["done"]:
        lines.append("### Done")
        lines.append("")
        for item in roadmap["done"]:
            lines.append(f"- ~~{item['title']}~~ (`{item['slug']}`)")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Write-if-changed helper
# ---------------------------------------------------------------------------

def write_if_changed(path: Path, content: str) -> bool:
    """Write content to path only if it differs from what's already there.

    Avoids triggering file-watcher loops when the content hasn't changed.
    Returns True if the file was written, False if skipped.
    """
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate vault-state.md context snapshot from SQLite."
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing vault-state.md",
    )
    parser.add_argument(
        "--db",
        type=Path,
        default=None,
        help="Path to brain.db (overrides DB_PATH env var)",
    )
    args = parser.parse_args()

    db_path = args.db or DB_PATH

    if not db_path.exists():
        print(f"Error: database not found at {db_path}")
        print("Run `python brain/sync.py --once` first.")
        raise SystemExit(1)

    conn = get_read_conn(db_path)
    projects = query_projects(conn)
    roadmap  = query_roadmap(conn)
    conn.close()

    content = render(projects, roadmap)

    if args.stdout:
        print(content)
        return

    out_path = VAULT_PATH / "40-reference" / "vault-state.md"
    written = write_if_changed(out_path, content)

    total_projects = sum(len(v) for v in projects.values())
    total_roadmap  = sum(len(v) for v in roadmap.values())

    if written:
        print(f"✓ vault-state.md updated ({total_projects} projects, {total_roadmap} roadmap items) → {out_path}")
    else:
        print(f"  vault-state.md unchanged ({total_projects} projects, {total_roadmap} roadmap items)")


if __name__ == "__main__":
    main()
